# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
# exemptLabels:
# Label to use when marking an issue as stale
staleLabel: inactive
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically flagged for inactivity because it has not
  been acted upon in the last 90 days. It will be closed if no further activity
  occurs in the next 7 days. Please feel free to re-open to resurrect the change
  if you feel this has happened by mistake. Thank you for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Closing due to inactivity. Please re-open if you feel this is a mistake.
